local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>pf', function() builtin.find_files({find_command = {'rg', '--files', '--hidden', '-g', '!.git'}}) end, {})
vim.keymap.set('n', '<leader>pc', function() builtin.find_files({hidden=true, no_ignore=true, no_ignore_parent=true}) end, {})
vim.keymap.set('n', '<leader>pg', builtin.git_files, {})
vim.keymap.set('n', '<leader>ps', builtin.live_grep, {})
vim.keymap.set('n', '<leader>px', function() builtin.live_grep({ vimgrep_arguments = {
        'rg', '--color=never', '--no-heading', '--with-filename', '--line-number', '--column', '--smart-case', '-uu'
    }}) end, {})
vim.keymap.set('n', '<leader>pw', function() builtin.live_grep({grep_open_files=true}) end, {})
vim.keymap.set('n', '<leader>pb', builtin.buffers, {})
vim.keymap.set('n', '<leader>ph', builtin.help_tags, {})
vim.keymap.set('n', '<leader>pk', builtin.keymaps, {})
vim.keymap.set('n', '<leader>pr', builtin.registers, {})
vim.keymap.set('n', '<leader>po', builtin.oldfiles, {})
vim.keymap.set('n', '<leader>pt', builtin.vim_options, {})
vim.keymap.set('n', '<leader>pm', builtin.man_pages, {})
vim.keymap.set('n', '<leader>pd', function() builtin.diagnostics({bufnr=0}) end, {})
vim.keymap.set('n', '<leader>pa', builtin.git_branches, {})
