# Change prefix to Ctrl-a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Use - and | to split windows
# Make new panes/windows with the current working directory
bind c new-window -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# Use 'r' to reload config file
bind r source-file ~/.tmux.conf

# Use alt + arrow keys to switch between panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Mouse mode on
set -g mouse on

# Keep 10000 lines of terminal history
set-option -g history-limit 10000
# Turn off autorenaming of windows
set-option -g allow-rename off

# Use vi commands
set-window-option -g mode-keys vi

# Send pane to or join pane from window
bind-key j command-prompt -p "Join pane from: " "join-pane -s '%%'"
bind-key s command-prompt -p "Send pane to: " "join-pane -t '%%'"
