# https://github.com/rose-pine/neovim/blob/main/lua/rose-pine/palette.lua
set -g status-style bg='#26233a',fg='#e0def4' # 'overlay', 'text'
set -g window-status-format ' #I #{?window_name,#{window_name} ,}'
set -g window-status-current-format '#[bg=#e0def4,fg=#000000] #I#{?window_zoomed_flag,*,} #{?window_name,#{window_name} ,}'
set -g status-right '#{?client_prefix,#{l:#[bg=#e0def4,fg=#000000]},} #{session_name} '
set -g status-left ''
