set -g @plugin 'tmux-plugins/tpm'

# Bind/unbind is cumulative so reloading file doesn't work. The only way to
# reload the default keybinds is to kill all tmux sessions (bad) or to use this
# hack which unbinds everything, and rebinds the default keys
unbind-key -a # 'prefix' table
unbind-key -a -T root
source-file ~/dotfiles/tmux/tmux_reset.conf

# Fix colors
set -g default-terminal "tmux-256color"

set-option -sg escape-time 10

# Have consistent nvim and tmux pane navigation
source-file  ~/.config/tmux/tmux_nvim.conf
# <C-l> is now taken, so do the following remap:
# Prefix <C-l> now does that
bind C-l send-keys 'C-l'

# Allow toggling to send all keybinds to nested session
set -g @plugin 'MunifTanjim/tmux-suspend'
set -g @suspend_key 'C-b'

# Theme
source-file ~/.config/tmux/tmux_theme.conf

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Change prefix to Ctrl-a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Make new panes/windows with the current working directory
bind c new-window -c "#{pane_current_path}"
bind '%' split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

# Use 'r' to reload config file
bind r source-file ~/.config/tmux/tmux.conf

# Mouse mode on
set -g mouse on

# Keep 100000 lines of terminal history
set-option -g history-limit 100000

# Turn off autorenaming of windows
set-option -g allow-rename off

# Use vi commands
set-window-option -g mode-keys vi

# Maybe need this for vim gutter?
set -g focus-events on

# Search sessions with fzf
bind b display-popup -E "tmux list-sessions | sed -E 's/:.*$//' | fzf --preview= | xargs -i tmux switch-client -t '{}'"

# Search panes with fzf
bind v display-popup -w '95%' -h '80%' -E "~/dotfiles/bin/tmux_pane_finder"

set -g @tm-macro-files '~/dotfiles/tmux/synced_macros.json ~/dotfiles/tmux/non_synced_macros.json'
run-shell ~/dotfiles/tmux-macros/main.py

bind h new-session

bind '*' kill-session
# No prompt
bind & kill-window
bind x kill-pane

# Resize the current pane using Alt + direction
bind -n M-k resize-pane -U 4
bind -n M-j resize-pane -D 4
bind -n M-h resize-pane -L 4
bind -n M-l resize-pane -R 4

# Easier scrollback binding
bind -n M-u copy-mode

# Switch to a different session when we kill the last terminal in current session
set-option -g detach-on-destroy off

# Always run this at the end
run '~/.tmux/plugins/tpm/tpm'
