# Note - tmux 3.1 is needed for this file to be automatically sourced

# Plugins
set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'catppuccin/tmux'
# TODO - fix the icons here
set -g @catppuccin_status_modules "directory session date_time"
set -g @catppuccin_date_time_text "%d-%m-%y %H:%M"

set -g @catppuccin_window_current_fill "all"
set -g @catppuccin_window_default_fill "all"
set -g @catppuccin_window_current_text "#W"
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_left_separator "█"
set -g @catppuccin_window_right_separator "█ "
set -g @catppuccin_window_middle_separator " | "

set -g @catppuccin_status_fill "all"
set -g @catppuccin_status_left_separator "█"
set -g @catppuccin_status_right_separator "█"

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Change prefix to Ctrl-a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Use - and | to split windows
# Make new panes/windows with the current working directory
bind c new-window -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# Use 'r' to reload config file
bind r source-file ~/.config/tmux/tmux.conf

# Mouse mode off
set -g mouse off

# Keep 10000 lines of terminal history
set-option -g history-limit 10000
# Turn off autorenaming of windows
set-option -g allow-rename off

# Use vi commands
set-window-option -g mode-keys vi

# Send pane to or join pane from window
# bind-key j command-prompt -p "Join pane from: " "join-pane -s '%%'"
bind-key s command-prompt -p "Send pane to: " "join-pane -t '%%'"

# Vim binds for moving between panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Always run this at the end
run '~/.tmux/plugins/tpm/tpm'
