set -g @plugin 'will-lynas/catppuccin' # Use my fork to stop interface changing every two days
set -g @catppuccin_status_modules_right "host session date_time"
set -g @catppuccin_date_time_text "%H:%M"

set -g @catppuccin_window_current_fill "all"
set -g @catppuccin_window_default_fill "all"
set -g @catppuccin_window_current_text "#W"
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_left_separator "█"
set -g @catppuccin_window_right_separator "█"
set -g @catppuccin_window_middle_separator "/"

set -g @catppuccin_status_fill "all"
set -g @catppuccin_status_left_separator "█"
set -g @catppuccin_status_right_separator "█"

set -g @catppuccin_host_icon "null"
set -g @catppuccin_session_icon "null"
set -g @catppuccin_date_time_icon "null"

# Grey out the status bar when we are in nested session
set -g @suspend_on_resume_command "tmux \
  set -ug @catppuccin_host_color \\; \
  set -ug @catppuccin_session_color \\; \
  set -ug @catppuccin_date_time_color \\; \
  run '~/.tmux/plugins/tpm/tpm' \\; \
"
set -g @suspend_on_suspend_command "tmux \
  set -g @catppuccin_host_color 'white' \\; \
  set -g @catppuccin_session_color 'white' \\; \
  set -g @catppuccin_date_time_color 'white' \\; \
  run '~/.tmux/plugins/tpm/tpm' \\; \
"
