export INSTALL_DIR="$HOME/dotfiles"
export ZSH_DIR="$INSTALL_DIR/zsh"
export PLUGIN_HOME="$HOME/.zsh_plugins"
export P10K_HOME="$PLUGIN_HOME/powerlevel10k"
export ZSH_VI_MODE_HOME="$PLUGIN_HOME/zsh-vi-mode"

mkdir -p "$PLUGIN_HOME"

if [[ ! -d "$P10K_HOME" ]]; then
    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $P10K_HOME
fi

if [[ ! -d "$ZSH_VI_MODE_HOME" ]]; then
    git clone https://github.com/jeffreytse/zsh-vi-mode.git $ZSH_VI_MODE_HOME
fi

if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
source $P10K_HOME/powerlevel10k.zsh-theme
source ~/.p10k.zsh

source $ZSH_VI_MODE_HOME/zsh-vi-mode.plugin.zsh
export ZVM_VI_EDITOR="nvim"
export ZVM_VI_ESCAPE_BINDKEY="^["
export ZVM_VI_INSERT_ESCAPE_BINDKEY=$ZVM_VI_ESCAPE_BINDKEY
export ZVM_LINE_INIT_MODE=$ZVM_MODE_INSERT

source $ZSH_DIR/zplug.zsh
source $ZSH_DIR/fzf.zsh
source $ZSH_DIR/pyenv.zsh
source $ZSH_DIR/settings.zsh
source $ZSH_DIR/aliases.zsh
source $ZSH_DIR/tpm.zsh
source $ZSH_DIR/rust.zsh
source $ZSH_DIR/secrets.zsh

# Enable autocompletion
autoload -Uz compinit && compinit

source $ZSH_DIR/zoxide.zsh

