export INSTALL_DIR="$HOME/dotfiles"
export ZSH_DIR="$INSTALL_DIR/zsh"

source $ZSH_DIR/zplug.zsh
source $ZSH_DIR/fzf.zsh
source $ZSH_DIR/pyenv.zsh
source $ZSH_DIR/settings.zsh
source $ZSH_DIR/aliases.zsh
source $ZSH_DIR/tpm.zsh
source $ZSH_DIR/rust.zsh

# Enable autocompletion
autoload -Uz compinit && compinit
