source ~/.powerlevel10k/powerlevel10k.zsh-theme
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
[[ ! -f ~/dotfiles/zsh/p10k.zsh ]] || source ~/dotfiles/zsh/p10k.zsh


source ~/dotfiles/zsh/scripts/all.sh
export PATH="$PATH:$HOME/.ghcup/bin/:$HOME/.cabal/bin/:$HOME/dotfiles/bin/"


source ~/.you-should-use/you-should-use.plugin.zsh
export YSU_MESSAGE_POSITION="after"
export YSU_HARDCORE=0
export YSU_MESSAGE_FORMAT="$(tput setaf 5)%alias = %command$(tput sgr0)"

source $HOME/.zsh-vi-mode/zsh-vi-mode.plugin.zsh
export ZVM_VI_EDITOR=nvim
export ZVM_VI_ESCAPE_BINDKEY=^[
export ZVM_VI_INSERT_ESCAPE_BINDKEY=$ZVM_VI_ESCAPE_BINDKEY
export ZVM_LINE_INIT_MODE=$ZVM_MODE_INSERT

# fzf ctrl-r is overwritten in insert mode.
function fix_ctrl_r(){
    source ~/.config/fzf/fzf.zsh
}
zvm_after_init_commands+=(fix_ctrl_r)

source ~/.zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

export HISTFILE=~/.zsh_history
export HISTFILESIZE=1000000000
export HISTSIZE=1000000000
export SAVEHIST=1000000000

setopt INC_APPEND_HISTORY
setopt EXTENDED_HISTORY

export PROMPT_EOL_MARK=''

preexec() {
    if [ -n  "$TMUX" ]; then
        mkdir -p "/tmp/tmux_pane_history"
        echo "$1" >> "/tmp/tmux_pane_history/${TMUX_PANE:1}"
    fi
}

eval "$(direnv hook zsh)"
